### ISSUE TITLE
Ember 3.x compatibility appears broken since 1.5.0

### ISSUE THREAD

**Issue by bjornharrtell** [sinankeskin/ember-picker#7]
It simply doesn't popup - no error messages.

**Comment by sinankeskin** [comment]
![image](https://user-images.githubusercontent.com/2091777/199570923-a5556f47-89a1-4115-a061-660446d59421.png)

Works just fine latest version with ember v3.26 @bjornharrtell

**Comment by bjornharrtell** [comment]
Hmm strange, must be something else then.

**Comment by sinankeskin** [comment]
Thanks for the reports. Feel free to reach out again or re-open this if you still see the issue. @bjornharrtell
